### ISSUE TITLE
Reboot Loop since v2.15.01 if DECONZ_VNC_MODE=1

### ISSUE THREAD

**Issue by m4d-maNu** [deconz-community/deconz-docker#100]
Hi,
if `DECONZ_VNC_MODE=1` then I have an reboot Loop with the deConz Docker-Container. If `DECONZ_VNC_MODE=0` then runs it.

VNC mode still worked with older versions, maybe even with 2.15.0, unfortunately I didn't test it at the time. With 2.14.xx the VNC mode definitely still worked.

Edit:
I tested, with 2.14.01 works the VNC Mode an since 2.15.0 is the reboot Loop.

**Comment by LukasA83** [comment]
Same here, after re-creating the container the issue went away. No change on the configs or host.

**Comment by senilio** [comment]
Are you Synology users?

**Comment by LukasA83** [comment]
No, running docker on Raspi 4b w. 4GB with Ubuntu 20 64bit.

**Comment by m4d-maNu** [comment]
> Are you Synology users?

Yes, I‘m a Synology User.

**Comment by nliaudat** [comment]
Here is the synology docker log : 
`<html><body>


2022-04-19 21:10:25 | stdout | This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
-- | -- | --
2022-04-19 21:10:25 | stdout | qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
2022-04-19 21:10:25 | stdout | qt.qpa.xcb: could not connect to display :0
2022-04-19 21:10:24 | stdout | [deconzcommunity/deconz] NOVNC port: 6080
2022-04-19 21:10:24 | stdout | - Backgrounding (daemon)
2022-04-19 21:10:24 | stdout | - SSL/TLS support
2022-04-19 21:10:24 | stdout | - Web server. Web root: /usr/share/novnc
2022-04-19 21:10:24 | stdout | - Listen on :6080
2022-04-19 21:10:24 | stdout | WebSocket server settings:
2022-04-19 21:10:24 | stdout | tigervncserver: Could not acquire fully qualified host name of this machine.
2022-04-19 21:10:24 | stdout | hostname: Name or service not known
2022-04-19 21:10:22 | stdout | tigervncserver: Could not acquire fully qualified host name of this machine.
2022-04-19 21:10:22 | stdout | hostname: Name or service not known
2022-04-19 21:10:22 | stdout | [deconzcommunity/deconz] VNC port: 5900
2022-04-19 21:10:21 | stdout | [deconzcommunity/deconz] Checking device group ID
2022-04-19 21:10:21 | stdout | [deconzcommunity/deconz] Modifying user and group ID
2022-04-19 21:10:21 | stdout | [deconzcommunity/deconz] Websockets port: 8443
2022-04-19 21:10:21 | stdout | [deconzcommunity/deconz] Web UI port: 8080
2022-04-19 21:10:21 | stdout | [deconzcommunity/deconz] Current deCONZ version: 2.15.01
2022-04-19 21:10:21 | stdout | [deconzcommunity/deconz] Starting deCONZ...
2022-04-19 21:10:03 | stdout |  
2022-04-19 21:10:03 | stdout | Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.


</body>
</html>`

**Comment by nliaudat** [comment]
I mean that's related to remove of 
`ARG DEBIAN_FRONTEND=noninteractive`
in dockerfile

**Comment by phdelodder** [comment]
> I mean that's related to remove of `ARG DEBIAN_FRONTEND=noninteractive` in dockerfile

In the docker file there is still `ENV DEBIAN_FRONTEND=noninteractive` being set

**Comment by phdelodder** [comment]
@nliaudat Can you see if you specified a hostname? 

As this is the first error msg  `tigervncserver: Could not acquire fully qualified host name of this machine.`

**Comment by nliaudat** [comment]
@phdelodder The network is in host mode, and the hostname is set for synology nas and resolves good

**Comment by phdelodder** [comment]
> @phdelodder The network is in host mode, and the hostname is set for synology nas and resolves good

This issue is that the tigervnc can't resolve the hostname, there are cases that it also crashes for that reason. Can you try disabling VNC and shell into the docker container and try to resolve the hostname.

**Comment by nliaudat** [comment]
`cat /etc/hostname  >                                    
deconzcommunity`
`cat /etc/hosts  >                                        
127.0.0.1       localhost                                                       
::1             localhost                                                       
127.0.0.1       nas-xxx                                                          
::1             nas-xxx  `

The common tools like hostnamectl, ping, dig, host, etc are not available

**Comment by phdelodder** [comment]
Can you add deconzcommunity to hosts and retry with enabling VNC?

**Comment by nliaudat** [comment]
is that related to issue #64 ?

**Comment by phdelodder** [comment]
> is that related to issue #64 ?

Indeed, specifying a hostname causes it to be unable to define the host error. So removing it from the config should solve it.

**Comment by MDXDave** [comment]
Set `DECONZ_VNC_MODE=0` and restart the container.

Then enter the docker container via `docker exec -it deconz /bin/bash`.

Navigate to `/tmp` and delete the file `.X0-lock` and `.X11-unix/X0`.

Stop container and set `DECONZ_VNC_MODE=1` and restart the container.

The bootloop should be gone.

**Comment by nliaudat** [comment]
> Set `DECONZ_VNC_MODE=0` and restart the container.
> 
> Then enter the docker container via `docker exec -it deconz /bin/bash`.
> 
> Navigate to `/tmp` and delete the file `.X0-lock` and `.X11-unix/X0`.
> 
> Stop container and set `DECONZ_VNC_MODE=1` and restart the container.
> 
> The bootloop should be gone.

Confirmed to work. Many thanks. 
`cd /tmp`
`rm -Rf .X*`

**Comment by xxLeoxx93** [comment]
> Set `DECONZ_VNC_MODE=0` and restart the container.
> 
> Then enter the docker container via `docker exec -it deconz /bin/bash`.
> 
> Navigate to `/tmp` and delete the file `.X0-lock` and `.X11-unix/X0`.
> 
> Stop container and set `DECONZ_VNC_MODE=1` and restart the container.
> 
> The bootloop should be gone.

I din't have any of these files in the folder, still I'm not able to boot with VNC enabled. Do I still need to edit the host file? If so how can I add this?

**Comment by senilio** [comment]
Please get the latest image and try again, see https://github.com/deconz-community/deconz-docker/pull/107

**Comment by yreiser** [comment]
Even with the latest image, I have the same problem.
Back to 2.14.00 is the only solution that works for me!

**Comment by yreiser** [comment]
Updated linux from buster to bullseye... everything works fine again.

**Comment by xjrcode** [comment]
Lastest version works (unhealthy) without VNC but doesn't even removing locked sessions.

```
=================== tail /home/deconz/.vnc/raspberrypi:5900.log ===================
===================================================================================

tigervncserver: /usr/bin/Xtigervnc did not start up, please look into '/home/deconz/.vnc/raspberrypi:5900.log' to determine the reason! -1
Killing Xtigervnc process ID 46... which seems to be deadlocked. Using SIGKILL!
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f92520 (most recent call first):
<no Python frame>
[deconzcommunity/deconz] NOVNC port: 6080
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[deconzcommunity/deconz] Starting deCONZ...
[deconzcommunity/deconz] Current deCONZ version: 2.15.03
[deconzcommunity/deconz] Web UI port: 80
[deconzcommunity/deconz] Websockets port: 443
[deconzcommunity/deconz] Using options --auto-connect=1         --appdata=/opt/deCONZ         --dbg-info=1         --dbg-aps=0         --dbg-zcl=0         --dbg-ddf=0         --dbg-dev=0         --dbg-zdp=0         --dbg-ota=0 	--dbg-error=0         --http-port=80         --ws-port=443
[deconzcommunity/deconz] Modifying user and group ID
[deconzcommunity/deconz] Checking device group ID
[deconzcommunity/deconz] VNC port: 5900
tigervncserver: No VNC server running for this user!

TigerVNC server sessions:

X DISPLAY #	RFB PORT #	PROCESS ID	SERVER
```

**Comment by Jo-Be-Co** [comment]
Uh - this log is hard to read. Is this only one log (i.e. the console output) for one start?

The `python` part is new to me - never seen this before.

Maybe you could start with `DECONZ_START_VERBOSE` set to `1`. So the statements itself would be logged. This when it becomes clearer which statements leads to which outpu.

**Comment by Jo-Be-Co** [comment]
... and to get this more focused to the problem you could also set `DECONZ_NOVNC_PORT` to `0` so the noVNC part would be skipped.
