### ISSUE TITLE
GCFFlasher_internal no devices found

### ISSUE THREAD

**Issue by williamledda** [deconz-community/deconz-docker#245]
Hello, 
I have a Conbee III  attached to a raspberry 4 on /dev/ttyUSB0.
I managed to run the container successfully by setting the baud rate option, and seems that the communication is fine (at least I can see the firmware id in the gateway page of Phoscon app), but if I run the command `GCFFlasher_internal` from inside the container I get "No device found".

```
# GCFFlasher_internal -l
no devices found
Path              | Serial      | Type
------------------+-------------+---------------
```

Any idea?
Thank you

William

**Comment by paclema** [comment]
It also happened to me with the latest "stable" version. If I use the image: deconzcommunity/deconz:2.23.02 my Raspbee is not only detected in the host but also in the docker container!

**Comment by senilio** [comment]
I don't know why this behavior has changed, but I'm leaning towards starting to recommend users to _not_ use this container for firmware patching since Docker adds a layer of complexity into flashing a device connected to the host.

Instead it would make more sense to:

1. Download the correct flasher binary from here: https://github.com/dresden-elektronik/gcfflasher/releases and unpack.
2. Download the wanted firmware file from https://deconz.dresden-elektronik.de/deconz-firmware/ and place it next to the unpacked flasher binary.
3. If running, stop the deCONZ docker container to make sure nothing is using the device.
4. `./GCFFlasher4 -l`
5. `./GCFFlasher4 -f firmware_file -d /dev/yourdevice -t 60` - modify device to what is listed from step 4.

Any issues with this method should be reported in the GCFflasher repo, since firmware flashing support is getting a bit out of scope for this project :)
