### ISSUE TITLE
Beta statt Stable wird über Docker Compose geladen

### ISSUE THREAD

**Issue by unstressable** [deconz-community/deconz-docker#262]
In der Docker Compose:
"image: deconzcommunity/deconz:stable"

Geladen wird dann 2.27.6

Lt. Changelog ist 2.26.3 die letzte stable und 2.27.1 die letzte beta.
2.27.6 wird dort gar nicht erwähnt:
https://phoscon.de/de/changelog/

Was ist nun richtig?

Kann ich mit "image: deconzcommunity/deconz:stable" sicher gehen, dass ich immer nur stabile versionen habe?

**Comment by bluemoehre** [comment]
Ich bin auch irritiert. Vor allem funktioniert Phoscon bei mir nicht mehr. Es werden keine Controller auf der Startseite angezeigt. Nur massig Fehler in der Console.

**Comment by mattreim** [comment]
The official deConz release overview is this: [deconz-rest-plugin](https://github.com/dresden-elektronik/deconz-rest-plugin/releases)

**Comment by unstressable** [comment]
@bluemoehre hab das selbe Phänomen.
bei mir wird ab 2.27.1 der Conbee 2 nicht mehr auf der Startseite angezeigt. Konfiguration also nicht mehr möglichY

2.27.0 geht einwandfrei.
Hast du die auch probiert?

**Comment by bluemoehre** [comment]
Nein, zu der Stunde wollte ich einfach nur in der Lage sein möglichst schnell das Licht wieder steuerbar zu haben.

**Comment by unstressable** [comment]
Dann wird das wohl die letzte funktionierende sein, zumindest habe ich das so festgestellt.
Sollten wir ein issue zu aufmachen?

**Comment by manup** [comment]
Hey everyone, latest stable version is v2.27.6 (beta tag is always bumped too so that it never points to an older number).
Due vacation time we're a bit behind updating the changelog on phoscon.de which will be fixed in the upcoming days.

The english more detailed changelog can be found in the Github releases: https://github.com/dresden-elektronik/deconz-rest-plugin/releases

The problem with Phoscon App (the Webapp) not loading correctly was unfortunately not be spotted before v2.27.6 release. However a simple **workaround** is to to open the Phoscon App as `http://<ipaddress>/pwa` which should load the right page and show the gateway to login.

This is fixed in https://github.com/dresden-elektronik/deconz/commit/0995e424ed7c23b287a9ade7ae75d716f505e99c and will be available in the next release.

**Comment by unstressable** [comment]
thanks a lot for explanation.
So I'll wait for the fix and update to it then.
