### ISSUE TITLE
Deconz for Cisco Access Points

### ISSUE THREAD

**Issue by jep78** [deconz-community/deconz-docker#43]
Hi,
on Cisco Wifi access points there is an possibility to install a docker container and use the USB port for some communication technologies. I want to use Conbee USB stick on this access point and control some Philipps lights.

https://developer.cisco.com/docs/app-hosting-ap/#!application-hosting-on-cisco-catalyst-access-points-application-hosting-on-cisco-catalyst-access-points

The problem is now the available diskspace on these access points. According the Cisco guide, the app (container) should not exceed 60MByte. The deoncz-docker is more ore less 650MByte. 

My question is, is there a possibility to shrink the container, so that it fits to the disk on these access points? Just install the minimum required software to control the Conbee stick with API? Or is everything required, that is in the actual Dockerfile?

Platform on the access point is: ARM/64

Thanks for your help,
Jonas

**Comment by senilio** [comment]
I agree the image is bigger than it should be, but reducing it isn't really in scope of or a priority in this project as we aim to provide a complete install with a graphical interface available over VNC :)

You can always try building your own using the Dockerfile and files from this repo: remove everything related to Qt5 and VNC and see what size you end up with. Also the start.sh needs to be edited so it doesn't try to run the GUI or VNC services. Please let us know if you succeed. 

I doubt that getting below 64MB is even possible, as the base image is roughly 23MB, and then we have the deconz package which by itself is 38MB after install. In addition to this there's a few other dependencies required for deCONZ in order to get it running.

**Comment by jep78** [comment]
thanks a lot for your answer! I will try to shrink the image with your input and I let you know :-)

**Comment by phdelodder** [comment]
For the minimal you still need QT5, which has a hugh dependency tree. So it won't be easy.

**Comment by jep78** [comment]
ok, thanks!
So I think (at least for me :)) it is not possible...

**Comment by senilio** [comment]
Closing this... feel free to reach out on Discord if you make any progress or want assistance.
