### ISSUE TITLE
Consider graceful shutdown of the deconz app

### ISSUE THREAD

**Issue by nachevn** [deconz-community/deconz-docker#49]
Currently after execution of a docker stop command the deconz tool is killed by Docker, please consider graceful stop of the deconz tool. I find an example here on how to do this within a shell script: https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86

**Comment by phdelodder** [comment]
I'll check it out, thanks for the tip!

**Comment by Jo-Be-Co** [comment]
This should go straight forward in a shell:

Instead of running `deCONZ` directly via `sudo` it should be started as a subprocess by adding a `&` to the call. Doing this the startup script stays in control and should note down the process id of the started `sudo`. Next the script should wait for the subprocess to end:
```sh
sudo -u deconz /usr/bin/deCONZ $DECONZ_OPTS &
SUDO_PID=$!
wait $SUDO_PID
```
Looks like these changes are good for nothing 😜  But doing so the script would be able to catch some signals and send some to the sudo task. **Before** running the above lines to following is needed:
```sh
signal_handler() {
    kill -s SIGTERM $SUDO_PID
}
trap signal_handler SIGTERM
```

`SIGTERM` should be the signal which will be received in the docker context. One could add some more signals to the trap command like `trap signal_handler SIGTERM SIGINT`.
In some implementations the trap function counts its calls. For example on handling `CRTL-C` from the shell. The script send two times a termination request (SIGTERM). The third time it is invoked, the process is to be killed with SIGKILL. Doing this the script regains controll (at the call of `wait`) to cleanup a little bit, delete some file and so on ...
Maybe the kill could not be invoked directly and another `sudo` is needed.
I don't know if SIGTERM is the correct way to stop `deCONZ` - but this should be the way regarding standards.

**Comment by senilio** [comment]
As the PR is now merged, I'm assuming this can now be closed.
