### ISSUE TITLE
Anyone running it on Synology DSM7.0?

### ISSUE THREAD

**Issue by DominikReber** [deconz-community/deconz-docker#54]
Hi

Currently I am using the marthoc docker image on  Synology 918+ with DSM 7.0
After enabling third party USB sticks (DSM 7.0 does not support it natively), I am able to use that docker image.

Now Ibwanted to switch to the new/your docker image. 
Unfortunately somehow it does not recognize the USB stick (Conbee II), even though I have the dame docker settings.

The gateway page shows that no stick is available amd also while using VNC, I cannot connect to the conbee II.

Turning off this docker image and restarting the mathoc version and the stick gets recognized again. 

Anyone succeeded?

I've tried stable and latest

Thanks

**Comment by senilio** [comment]
The issue here is that the user running deCONZ doesn't have permission to access the USB stick. There's a few things to try:

Check the permissions on the usb device in /dev. Make sure that the UID running deCONZ have access to it.
The quick and dirty workaround until something better is implemented is to set DECONZ_UID and DECONZ_GID environment variables to 0, which will run deCONZ as root like it did before.

**Comment by DominikReber** [comment]
Hi and thanks for your comment

This solved it, thanks a lot!

**Comment by wimmio** [comment]
Hello,
I tried installing it on 720+ with DSM 7. When i connect to the frontend it sees my Conbee 2 usb stick, but when i click it it goes to the login page. 

I  didn't get the chance to create a password and default password doesn't work.

Trying to reset the password also doesn't work.

Any ideas?

Thanks.

**Comment by phdelodder** [comment]
Please check https://github.com/dresden-elektronik/deconz-rest-plugin, this seems not related to docker
