### ISSUE TITLE
Error: Process request took to long (domoticz/deconz)

### ISSUE THREAD

**Issue by niawag** [deconz-community/deconz-docker#94]
Hi and thanks a lot for this usefull docker image, I have been running it (and Marthoc image) from a long time and I'm having this error several times a day.
Here is the exact message: 
`2022-04-07 09:00:14.386 Error: deCONZ: Process request took to long: 1.0878868103027344 s`
And the log surrounding it:
```
2022-04-07 09:00:13.143 PiScreen Control (dummy hard): Light/Switch (PiScreen Control)
2022-04-07 09:00:13.261 deCONZ: onCommand called for Unit 22: Parameter 'On', Level: 0, Hue:
2022-04-07 09:00:13.076 Status: Incoming connection from: 192.168.0.44
2022-04-07 09:00:13.125 Status: User: Admin (IP: 192.168.0.44) initiated a switch command (95/PiScreen Control/Set Level)
2022-04-07 09:00:14.386 Error: deCONZ: Process request took to long: 1.0878868103027344 s
2022-04-07 09:01:03.722 Status: Notification sent (Email)
```
The request time can go up to 5 s and seems to match with a high CPU usage on my Pi3b.

Some intel on my setup:
Hardware : Raspberry Pi 3b
Docker version 20.10.11, build dea9396
docker-compose version 1.27.4, build 40524192
Domoticz and deconz : latest
deconz compose:
```
  deconz:
    container_name: deconz
    image: deconzcommunity/deconz:latest
    environment:
      - PUID=1000
      - PGID=1000
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=8088
      - TZ=Europe/Paris
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=*hidden*
    volumes:
      - /home/pi/dockers/deconz:/opt/deCONZ
    network_mode: host
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2118459-if00:/dev/ttyACM0
    restart: always
```

Is this error normal ? What can I do to pinpoint the issue and try to fix it?

**Comment by senilio** [comment]
It's certainly not normal, but also very unlikely to be related to Docker. This goal of this project is to run the deCONZ application as-is inside a container.

Some things to check is:
- Which process is running high on CPU?
- What is happening on the docker host when you see issues?
- Is there interference in your network?

Here's a good troubleshooting guide for you to get started with https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Debugging-101

I think it's better for you to start a topic on the forum, since you're much more likely to get help there :) See https://forum.phoscon.de/

**Comment by niawag** [comment]
Hi and thanks for your help, I think I might have "solved" the problem by reducing the Pi3 load (moving some services on another host). I'll check if the error is gone for good and, if not, I'll ask the phoscon forum.
